image: archlinux
packages:
  - lua
  - meson
  - ninja
  - wayland
  - wayland-protocols
  - mesa
  - xorg-server-xwayland
  - cairo
  - xcb-util-image
  - libinput
  - pixman
  - libxkbcommon
  - gdk-pixbuf2
  - xcb-util-image
  - libcap
  - rustup
  - clang
  - libxcb
  - xcb-util-image
  - xcb-util-cursor
  - xcb-util-wm
sources:
  - https://github.com/way-cooler/way-cooler
tasks:
  - setup: |
      rustup install stable
      rustup install nightly
      rustup default stable
      rustup component add rustfmt-preview --toolchain nightly
      rustup component add clippy
  - way-cooler-common: |
      cd way-cooler
      CC=gcc meson build-gcc
      CC=clang meson build-clang
  - way-cooler-gcc: |
      cd way-cooler/build-gcc
      ninja
  - way-cooler-clang: |
      cd way-cooler/build-clang
      ninja
  - awesome: |
      cd awesome
      export CC=clang
      export RUST_BACKTRACE=full
      cargo build --verbose
      cargo test --verbose
      cargo +nightly fmt --all -- --check
      cargo clippy --all
