image: archlinux
packages:
  - lua
  - meson
  - ninja
  - wayland
  - wayland-protocols
  - mesa
  - xorg-server-xwayland
  - cairo
  - xcb-util-image
  - libinput
  - pixman
  - libxkbcommon
  - gdk-pixbuf2
  - xcb-util-image
  - libcap
  - clang
  - libxcb
  - xcb-util-image
  - xcb-util-cursor
  - xcb-util-wm
  - python
sources:
  - https://github.com/way-cooler/way-cooler
  - https://github.com/swaywm/wlroots
tasks:
  - check-c-style: |
      cd way-cooler
      python ./run-clang-format.py -r ./compositor/ ./client/
  - wlroots: |
      cd wlroots
      git checkout 0.6.0
      meson --prefix=/usr build -Drootston=false -Dexamples=false
      ninja -C build
      sudo ninja -C build install
  - way-cooler-common: |
      cd way-cooler
      CC=gcc meson build-gcc
      CC=clang meson build-clang
  - way-cooler-gcc: |
      cd way-cooler/build-gcc
      ninja
  - way-cooler-clang: |
      cd way-cooler/build-clang
      ninja
